CREATE SCHEMA IF NOT EXISTS TESTDB;
CREATE TABLE IF NOT EXISTS TESTDB.INVENTORY
(
    INVENTORYID VARCHAR NOT NULL PRIMARY KEY,
    ITEM VARCHAR,
    ITEMTYPE VARCHAR,
    COUNT INT,
    PRICE DOUBLE
);
CREATE TABLE IF NOT EXISTS TESTDB.USER
(
    USERID VARCHAR  NOT NULL PRIMARY KEY,
    FIRSTNAME VARCHAR,
    LASTNAME VARCHAR
);

CREATE TABLE IF NOT EXISTS TESTDB.USERCART
(
    USERID VARCHAR,
    INVENTORYID VARCHAR,
    ITEMTYPE VARCHAR,
    ITEMCOUNT INT,
    ITEMPRICE DOUBLE,
    PRIMARY KEY (USERID, INVENTORYID),
    FOREIGN KEY(USERID) REFERENCES TESTDB.USER,
    FOREIGN KEY(INVENTORYID) REFERENCES TESTDB.INVENTORY

);